services:
  - type: web
    name: aihub-pdf
    env: node
    plan: free
    buildCommand: |
      cd client && npm install && npm run build &&
      cd ../server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: RENDER_EXTERNAL_URL
        value: https://aihub-pdf.onrender.com
    autoDeploy: false